#
# REST Client Configuration for test enviranment (cloud)
#
# @author Alexander Krasnyanskiy
#
---
server:
  url: http://107.20.44.101/jasperserver-pro
  version: 5.6.0

  headers:
    accept: JSON
    content-type: JSON